### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Hold My Dice
# description: This will be meta HTML tag content. This can be ignored.
description: Quotes taken wildly out of context
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: "/hold_my_dice"

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: "#hold_my_dice"
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: Wild quotes out of context
# email: Your E-Mail address for the email button.
email: dev@voidnologo.com
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: voidnologo

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: What is going on here!?
# about_me_description: This will be displayed under the title.
about_me_description: We collect quotes taken wildly out of context and share them.  We remember the good times.  We remember the bad times.  But most of importantly, we remember.

# QUOTES SECTION
# > setting this to true, will display the Quotes section
# > setting this to false, will omit the Quotes section
show_quotes_card: true
# show_quotes:
# > setting this to true, will display your listed quotes in _data/quotes.yml
# > setting this to false, will omit your listed quotes
show_quotes: true
# quotes_title: The will be displayed as the title of your quotes
quotes_title: You said what now?

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: false
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact
# contact_description: This will be displayed under the title.
contact_description: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. If you like this theme and want to use it for yourself, checkout the source code and the documentation at <a class="highlight-link" href="https://github.com/longpdo/neumorphism" target="_blank" rel="noreferrer"> Github </a>.

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: voidnologo/quoter.site
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: true
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: true
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded


### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
